---
  title: "Untitled"
author: "Benjamin Avanzi"
date: "01/02/2021"
output:
  md_document:
  variant: markdown
---
  
  # A first R Course
  
  ## Overview of contents
  The contents include Base R, tidyverse, data visualisation, and document generation via R Markdown.

Main references are:
  
  - Base R: 
  - [The R Software](http://biostatisticien.eu/springeR/index-en.html)
- some LinkedIn Learning videos which are referenced in the materials
- tidyverse and advanced data visualisation:
  - [tidyverse](https://www.tidyverse.org)
- [R for Data Science](https://r4ds.had.co.nz)
- some LinkedIn Learning videos which are referenced in the materials
- advanced data visualisation:
  - [R for Data Science, "Communicate" section](https://r4ds.had.co.nz)
- [bookdown](https://bookdown.org)
- [blogdown](https://bookdown.org/yihui/blogdown/)
- some LinkedIn Learning videos which are referenced in the materials

## History
Those materials were created by the following people, while being employed in the institutions in parentheses

- [Benjamin Avanzi](http://www.benjaminavanzi.com) (University of New South Wales, University of Melbourne) --- for all contents
- [Pierre Lafaye de Micheaux](https://web.maths.unsw.edu.au/~lafaye/) (Université de Montréal, University of New South Wales, Université de Montpellier) --- especially for Base R contents
- Xinda Yang (University of New South Wales) --- especially for Base R contents and some tidyverse and data visualisation contents
- [Alan Xian](https://researchers.mq.edu.au/en/persons/alan-xian) (University of New South Wales, Macquarie University) --- especially for Base R contents and some tidyverse and data visualisation contents
- [Guillaume Boglioni Beaulieu](https://www.business.unsw.edu.au/our-people/Guillaume-Boglioni-Beaulieu) (University of New South Wales) --- especially for Base R contents and some tidyverse and data visualisation contents
- Arkington Owen (University of New South Wales) --- for Base R contents to a limited extent, but especially for the tidyverse, advanced data visualisation contents, and document generation via R Markdown contents

It all started with an initial set of slides on Base R that were created by [Pierre Lafaye de Micheaux](https://web.maths.unsw.edu.au/~lafaye/), and aligned with textbook [The R Software](http://biostatisticien.eu/springeR/index-en.html). Contents were then re-developped and augmented for a first year course taught by [Benjamin Avanzi](http://www.benjaminavanzi.com) collaboratively with Xinda Yang, which was subsequently taught by [Alan Xian](https://researchers.mq.edu.au/en/persons/alan-xian) and [Guillaume Boglioni Beaulieu](https://www.business.unsw.edu.au/our-people/Guillaume-Boglioni-Beaulieu). The tidyverse, advanced data visualisation, and document generation via R Markdown contents were developed for a data visualisation course by Benjamin Avanzi with the assistance of Arkington Owen.